FROM daocloud.io/library/java:8-jre
MAINTAINER "icyblazek@gamil.com"
ENV REFRESHED_AT 2017-09-06
USER root
WORKDIR /data/project
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo "Asia/Shanghai" > /etc/timezone
ADD classes/application-dev.properties application-dev.properties
ADD DGSC_JSJWebsocket-1.0.0-SNAPSHOT.jar DGSC_JSJWebsocket-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","-Dspring.config.location=application-dev.properties", "-Duser.timezone=GMT+08", "DGSC_JSJWebsocket-1.0.0-SNAPSHOT.jar"]